#!/usr/bin/env node
'use strict';

/**
 * postinstall.js
 *
 * On Windows, node-pty's build fails out of the box for three reasons:
 *
 *   1. winpty.gyp calls .bat helper scripts without the ".\" prefix that cmd.exe
 *      requires when NoDefaultCurrentDirectoryInExePath is set (default since
 *      Windows 10 21H1).  The scripts also produce paths with backslashes that
 *      Python 3 misinterprets as Unicode escape sequences (\U, \t, etc.).
 *      Fix: replace both shell-out calls with hardcoded values and pre-generate
 *      the header they would have produced.
 *
 *   2. binding.gyp enables Spectre mitigation ('/Qspectre'), which requires an
 *      optional Visual Studio component ("MSVC … Spectre-mitigated libs") that
 *      most developers don't have installed.
 *      Fix: disable Spectre mitigation in binding.gyp.
 *
 * These patches are applied before electron-rebuild runs so that `npm install`
 * succeeds on a stock Windows + VS Build Tools setup.
 */

const fs   = require('fs');
const path = require('path');
const { execSync } = require('child_process');

if (process.platform === 'win32') {
  const nodePtyDir = path.join(__dirname, '..', 'node_modules', 'node-pty');

  // ── 1. Pre-generate the version header ──────────────────────────────────
  const genDir     = path.join(nodePtyDir, 'deps', 'winpty', 'src', 'gen');
  const headerPath = path.join(genDir, 'GenVersion.h');
  const versionTxt = path.join(nodePtyDir, 'deps', 'winpty', 'VERSION.txt');

  fs.mkdirSync(genDir, { recursive: true });
  const version = fs.existsSync(versionTxt)
    ? fs.readFileSync(versionTxt, 'utf8').trim()
    : 'unknown';
  fs.writeFileSync(
    headerPath,
    `// AUTO-GENERATED by scripts/postinstall.js\n` +
    `const char GenVersion_Version[] = "${version}";\n` +
    `const char GenVersion_Commit[] = "none";\n`,
    'utf8'
  );

  // ── 2. Patch winpty.gyp ────────────────────────────────────────────────
  // Replace the two shell-out calls with literal values so gyp doesn't invoke
  // any .bat files and Python 3 doesn't choke on backslash-escape sequences.
  const gypPath = path.join(nodePtyDir, 'deps', 'winpty', 'src', 'winpty.gyp');
  if (fs.existsSync(gypPath)) {
    const lines   = fs.readFileSync(gypPath, 'utf8').split('\n');
    const patched = lines.map(line => {
      if (line.includes('WINPTY_COMMIT_HASH%') && line.includes('cmd /c')) {
        return "        'WINPTY_COMMIT_HASH%': 'none',";
      }
      if (line.includes('UpdateGenVersion') && line.includes('cmd /c')) {
        return "            'gen',";
      }
      return line;
    });
    fs.writeFileSync(gypPath, patched.join('\n'), 'utf8');
    console.log('[postinstall] Patched winpty.gyp (removed bat script calls).');
  }

  // ── 3. Patch binding.gyp ──────────────────────────────────────────────
  // Disable Spectre mitigation — the mitigated libs are an optional VS
  // component and not installed on most developer machines.
  const bindingPath = path.join(nodePtyDir, 'binding.gyp');
  if (fs.existsSync(bindingPath)) {
    const original = fs.readFileSync(bindingPath, 'utf8');
    const patched  = original.replace(/'SpectreMitigation': 'Spectre'/g, "'SpectreMitigation': 'false'");
    if (original !== patched) {
      fs.writeFileSync(bindingPath, patched, 'utf8');
      console.log('[postinstall] Patched binding.gyp (disabled Spectre mitigation).');
    }
  }

  // ── 4. Patch winpty.gyp — disable Spectre for all winpty targets
  // winpty's individual targets each set 'SpectreMitigation': 'Spectre', which
  // requires the optional "Spectre-mitigated libs" VS component.  Replace with
  // 'false' so the build works on a standard VS Build Tools install.
  if (fs.existsSync(gypPath)) {
    const original = fs.readFileSync(gypPath, 'utf8');
    const patched  = original.replace(/'SpectreMitigation': 'Spectre'/g, "'SpectreMitigation': 'false'");
    if (original !== patched) {
      fs.writeFileSync(gypPath, patched, 'utf8');
      console.log('[postinstall] Patched winpty.gyp (disabled Spectre mitigation).');
    }
  }
}

// Use the local binary path so this works both when called directly as
// `node scripts/postinstall.js` and from npm's postinstall hook
// (which adds node_modules/.bin to PATH automatically).
const rebuildBin = path.join(__dirname, '..', 'node_modules', '.bin', 'electron-rebuild');
execSync(`"${rebuildBin}" -f -w node-pty`, { stdio: 'inherit' });
